### PR TITLE
Updated the --> displayed on the nav barindex.html

### PR DESCRIPTION
**Pull request by HardikSo**
Removed the '-->' that was appearing on the top right side of the nav bar.

### CODE REVIEW

**Comment by HardikSo** [comment]
Sorry but I am not able to find the template to fill the PR. I looked up the previous PRs. Can you send that?

**Comment by Ryan10145** [comment]
@HardikSo Provide a preview link and the number of the issue that this fixes.

**Comment by Ryan10145** [comment]
@sarnava1 There's no PR template currently set up for this repository, which is probably leading to some confusion.

**Comment by HardikSo** [comment]
> @HardikSo Provide a preview link and the number of the issue that this fixes.
> Additionally, this is a duplicate of #21 and #18

But It wasn't fixed that is why I picked this. I cannot pull this request then?

**Comment by Ryan10145** [comment]
@HardikSo It is unnecessary to have 3 separate PRs, all created at different times, that all perform the exact same changes to fix the same issue. Github becomes cluttered with duplicate PRs. #18 is the only PR that should exist and be merged, as it was the original.

**Pull request closed without merging**
