### PR TITLE
Enhancement of 2019.fossasia.org homepage and exhibition page

### LINKED ISSUE #73: back to top with icon
In the Fossasia website(https://fossasia.org/) the back to top button is given but it is not in the form of icon it is in the left bottom which is not easily visible by the user due to they are not using so we can make this back to top option in the form of an icon

### PR DESCRIPTION
**Pull request by imrrahul**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

In this Pull Request I have solved the issues #73 #62  #47(similar),i.e, added the back to top button as previous back to top link was not properly visible and added the following other things --  

              1.) Added a back to top button (proper visibility)
              2.) Underline to footer menus to increase their visibility in the site.
              3.) Added new lines just below tweets in the footer as some large tweets were overlapping with  
                   `Follow @fossasia for more updates` text in the bottom.
             4.) Updated the custom.css file by adding extra css codes.
             5.) Solved Button does not show up correctly on Exhibition page by re-designing it
- Fixes #73 #62 #47 (similar)

## Description / Changes
The updated version will have the following updates/features-

             1.) Proper visible Back To Top button
             2.) Proper spacing between tweets and _Follow @fossasia for more updates_.\
             3.) Proper visibility footer menus.
             4.) Updated CSS file
             5.) Solved Button does not show up correctly on Exhibition page by re-designing it

## Screenshots if any:
screenshot from 2019-02-11 14-46-47

## Screenshot (Button):
Before
screenshot from 2019-02-11 19-35-42

After
screenshot from 2019-02-11 19-43-34

- - - - - - - - - - - -
## Preview link
https://imrrahul.github.io/preview/index.html

### CODE REVIEW

**Comment by imrrahul** [comment]
@mariobehling please review this once.

**Comment by imrrahul** [comment]
@plxity please review the changes , I have made following changes ---
1.)  Added smooth scrolling
2.)  Used the top arrow symbol instead of "Back to top"
3.) On hover button is not changing the colour to a grey shade.
4.) No underlining of the footer.
From the next time onwards my PR will be net and clean , 
Thank you!

**Comment by imrrahul** [comment]
@plxity please review the changes!! thank you

**Comment by mariobehling** [comment]
This PR changes the style of the page and makes it more different from the FOSSASIA main page. Therefore closing this PR. Thanks for your support!

**Comment by imrrahul** [comment]
thanks @mariobehling for the review looking forward to make changes.

**Pull request closed without merging**
