### PR TITLE
Updating the navigation bar of exhibition page

### LINKED ISSUE #92: Unresponsive navigation bar of exhibition page
**Actual Behaviour**
The Navigation Bar currently is not responsive of the exhibition page

**Expected Behaviour**
Navigation Bar should be responsive.

**Steps to reproduce it**
a) Go to 'https://2019.fossasia.org/exhibition/index.html'
b) Resize the browser screen.
c) See the issue, Fossasia logo merges with 'Home' and 'Tickets' link.

**Screenshots of the issue**
screenshot 2019-02-28 at 12 30 02 pm

**Would you like to work on the issue?**
I would like to take this issue.

### PR DESCRIPTION
**Pull request by kushthedude**
- [x] Included a screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Fixes #92 <Issue Number>

## Description / Changes
-Updated the navigation bar of 'Exhibition Page'
-Contents on the page dont overlap now with each other
-Preview Link: https://kushthedude.github.io/2019.fossasia.org/exhibition/index.html

### Before:
screenshot 2019-02-28 at 8 29 51 pm

### After:

screenshot 2019-02-28 at 8 30 06 pm

- - - - - - - - - - - -

### CODE REVIEW

**Comment by kushthedude** [comment]
@mariobehling ,
Sir,Please review this PR.

**Comment by kushthedude** [comment]
@pranav1698 Thanks but still its not merged yet.

**Comment by pranav1698** [comment]
Wait for @mariobehling to review

**Comment by yash-kedia** [comment]
u will need to provide a test link (gh-pages) to get merged.

**Comment by kushthedude** [comment]
@yash-kedia Actually i deleted the forked regarding this issue , Any possible solution you could tell.

**Comment by kushthedude** [comment]
@imrrahul Not a issue , Here is the link https://kushthedude.github.io/summit/exhibition/index.html
What now?

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by kushthedude** [comment]
@mariobehling Sir, 
As this Repo was accidentally deleted by me i have created a new PR with no conflicts from the Master branch you can review and check it #105

**Pull request closed without merging**
