### PR TITLE
Adding speakers into featured list

### LINKED ISSUE #106: Add featured speakers from eventyay to start page.
Eventyay has a featured speakers list. Please add the missing speakers to the start page: https://eventyay.com/e/3689bc98/

screenshot from 2019-03-07 13-00-30

### PR DESCRIPTION
**Pull request by kushthedude**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Added all the speakers in the featured list.

-https://kushthedude.github.io/2019.fossasia.org/

- Fixes #106  

## Description / Changes
Added all featured speakers from eventyay to 'index.html'.
-Images of some speakers were not present in 'img/' , So i have added some images in 'img/'.

- - - - - - - - - - - -

### CODE REVIEW

**Comment by kushthedude** [comment]
@mariobehling ,Sorry for all the previous errors , The preview link is working and i have taken care no where except the featured speaker section,Changes occurs.

**Comment by mariobehling** [comment]
Some images aren't cropped in ratio 1:1 resulting in issues. Please dont squeeze or stretch images, crop them instead to the right ratio.

**Comment by kushthedude** [comment]
@mariobehling ,Sir did the changes you specified but still some images are pixelated as after cropping them too the pixels are too low for it so it would be ugly.

**Comment by mariobehling** [comment]
Please keep the previous speakers on the top in the same order as before.
Please avoid adding a speaker twice.

**Comment by kushthedude** [comment]
@mariobehling ,Sir did the changes you asked.

**Comment by mariobehling** [comment]
A number of images are not exactly cropped 1:1. Width = Height.

**Comment by kushthedude** [comment]
@mariobehling ,Sir,Done and now it looks good.

**Comment by mariobehling** [comment]
Should we maybe leave it here? As this starts to take longer than expected, I am not sure how to proceed.

**Comment by kushthedude** [comment]
@mariobehling ,Sir,I would like to suggest all of this problem is getting caused because images of some speakers are not available in proper resolution . I would like to suggest that why not we remove those speakers whose image is not available in some good resolution ,As this will make the site look better and most of the speakers from event yay may also get included in the list.

**Comment by mariobehling** [comment]
Look, issues can be solved one after the other. We can get better photos in the next step. At first the basics need be right and just trying fix ratio of images the way you do it results in new issues. If reviewing an issues starts to take longer than resolving it, a project cannot progress. It is great for the community to learn something together, but we also need something that works for the intended purpose.

See, e.g. images are sqeezed in some resolutions:
screenshot from 2019-03-09 00-27-33

**Comment by kushthedude** [comment]
@mariobehling ,Sorry sir , But all this new issue is just being created due to-:
1.)The div container for the image is of 300*300 px(at max page size),all those images which are not available in 300*300 px will get pixelated.
2.)To solve the issue even if I scale the images ,The UI will get poor and the issue like the squeezing will occur as you mentioned above.
I tried to solve it but due to insufficient resources i messed up . But as i said above if you say i can make one last commit in which speakers with insufficient image will be removed and i can solve all the issues you stated above like the ratio and the scaling. Shall i proceed or should we stop ?

**Pull request closed without merging**
