### PR TITLE
fixed the extra space on the right

### PR DESCRIPTION
**Pull request by Dharmesh-Poddar**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [ ] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](url)

- Fixes #<Issue Number>

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by Dharmesh-Poddar** [comment]
screenshot from 2018-12-12 21-42-43

**Comment by Dharmesh-Poddar** [comment]
@plxity what's the issue with preview link

**Comment by plxity** [comment]
The preview link is not opening.

**Comment by Dharmesh-Poddar** [comment]
d

**Comment by Dharmesh-Poddar** [comment]
@abishekvashok  how can I get the preview link of changed website?

**Comment by Dharmesh-Poddar** [comment]
https://distracted-curran-26be47.netlify.com/

**Comment by mariobehling** [comment]
Closing due to inactivity. Please reopen once you would like to continue. Thanks.

**Pull request closed without merging**
