### PR TITLE
Adding schedule roster as html

### PR DESCRIPTION
**Pull request by kushthedude**
- [x] Included a screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Fixes #87 

## Description / Changes
-Changed index.html as per the requirements.
-Added table at the place of image in the place of schedule roster.
-Reference was made from updated RoomVisual.html

### Before:
<a href="https://imgflip.com/gif/2uox2t"></a>

### After:
<a href="https://imgflip.com/gif/2uowrt"></a>

- - - - - - - - - - - -

### CODE REVIEW

**Comment by kushthedude** [comment]
@mariobehling Sir ,
All the changes you requested have been done.
Please review it.

**Comment by mariobehling** [comment]
Thanks.

Please make "Thursday, March 14" into one line. Also make the first column to show the text in one line.

screenshot from 2019-02-27 03-17-32

**Comment by kushthedude** [comment]
@mariobehling 
Sure sir, will update PR after the specified changed

**Comment by kushthedude** [comment]
@mariobehling 
Sir,Please check the updated file.

**Comment by mariobehling** [comment]
Thank you!

**Comment by mariobehling** [comment]
Would be great if you could help with the update here as well: https://github.com/fossasia/2019.fossasia.org/issues/90

**Comment by kushthedude** [comment]
@mariobehling
Sure sir,Will look into it

**Pull request merged**
