### PR TITLE
Adding speakers into featured list

### LINKED ISSUE #106: Add featured speakers from eventyay to start page.
Eventyay has a featured speakers list. Please add the missing speakers to the start page: https://eventyay.com/e/3689bc98/

screenshot from 2019-03-07 13-00-30

### PR DESCRIPTION
**Pull request by kushthedude**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Added all the speakers in the featured list.

- [Preview Link](url)

- Fixes #106 

## Description / Changes
Added all featured speakers from eventyay to 'index.html'.
-Images of some speakers were not present in 'img/' , So i have added some images in 'img/'.

- - - - - - - - - - - -

### CODE REVIEW

**Comment by kushthedude** [comment]
@mariobehling , 
Sir , Sorry for taking long but took a while to add the speakers , Ready for review.

**Comment by mariobehling** [comment]
Please do the following:
* Only take the first sentence of the description
* Ensure all images are showing up
* Scale up images that are too small

-> check out your own deployment and identify issues.

**Comment by kushthedude** [comment]
@mariobehling ,
Sir, Since the pictures of some speakers are of less resolution if i will scale them up images will be pixelated and will look ugly on the page, If you say so we can remove the those speakers whose picture is not available in adequate quality ?

**Comment by kushthedude** [comment]
Sir , The commits you requested have been made , 
1.) Scaled up images.
2.)Ensured all the images are being displayed on my machine
3.)Only took a sentence or a paragraph for speaker bio.

**Comment by mariobehling** [comment]
Preview link does not show the speakers added.

**Comment by mariobehling** [comment]
Only change the relevant areas in index.html! Don't change other parts.

**Comment by kushthedude** [comment]
I am sorry for the indentation created by my IDE. Will resolve it and update the preview link

**Comment by kushthedude** [comment]
Closing via #112

**Pull request closed without merging**
