### PR TITLE
Added 404 and 500 Pages

### LINKED ISSUE #1: Template File still exists in 404 and 500 Pages
Template File still exists in 404 and 500 Pages
Screenshots
image
image

### PR DESCRIPTION
**Pull request by naveentherocker**
Fixes #1 
Preview Link - https://naveentherocker.github.io/2019.fossasia.org/404.html
Preview Link - https://naveentherocker.github.io/2019.fossasia.org/500.html

### CODE REVIEW

**Comment by naveentherocker** [comment]
@0x48piraj This must be on the Every Page. Because the existing one is the Template itself.

**Comment by 0x48piraj** [comment]
Yes @naveentherocker ! Just was messing around. Hope you do not mind it.

**Comment by naveentherocker** [comment]
@0x48piraj Fine Brother.

**Comment by mariobehling** [comment]
This website is probably getting deleted entirely and it is currently just a forward. Therefore this does not make sense and I am closing it.

**Pull request closed without merging**
