### PR TITLE
Decreasing Table Height

### LINKED ISSUE #107: Update Schedule Roster
Please ensure the line spacing in the schedule roster table is set to 1 and reduce their height of the table.

Thank you.

screenshot from 2019-03-07 20-54-10

### PR DESCRIPTION
**Pull request by kushthedude**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Decreased Table Height

- [Preview Link](url)

- Fixes #107 

## Description / Changes
Changed the line height column of table.

### Before:
screenshot 2019-03-07 at 10 57 06 pm

### After:
screenshot 2019-03-07 at 10 57 32 pm

- - - - - - - - - - - -

### CODE REVIEW

**Comment by kushthedude** [comment]
@mariobehling , Ready for review.

**Comment by mariobehling** [comment]
Please provide a working preview link.

**Comment by kushthedude** [comment]
@mariobehling , Sir , Preview link : https://kushthedude.github.io/2019.fossasia.org/

**Comment by mariobehling** [comment]
I need to revert this as it affected other parts of the site as well and distorted the design.

**Pull request merged**
