### PR TITLE
Updating the Schedule Roster

### LINKED ISSUE #98: Update Schedule Roster
There are a number of workshops added for the evening. Please use the "RoomVisual.html" to update the schedule roster.

screenshot from 2019-03-01 11-32-07

### PR DESCRIPTION
**Pull request by kushthedude**
- [x] Included a Screenshot after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Fixes #98 

## Description / Changes
-Made changes to 'index.html' as were described in updated 'RoomVisual.html'
-Made check that all the dates appear in one line.
-Made check that first column is displayed in one row.

### Before:
screenshot 2019-03-02 at 11 05 51 pm

### After:
screenshot 2019-03-02 at 11 05 21 pm

- - - - - - - - - - - -

### CODE REVIEW

**Comment by kushthedude** [comment]
Corrected the space issues.

**Comment by kushthedude** [comment]
@mariobehling ,
Sir,Issue is ready for review and can you please also review #97

**Comment by mariobehling** [comment]
Thank you.

**Comment by mariobehling** [comment]
@kushthedude Interested to follow up here: https://github.com/fossasia/2019.fossasia.org/issues/103

**Pull request merged**
