### PR TITLE
(#32)Added Back to Top Button

### LINKED ISSUE #32: Add a Back to Top button
A responsive back-to-top button should be added, I'm working on this

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #32 
Added a Back to Top Button to the website(red)
It looks good and is responsive(shows up when you scroll down )

[Preview](https://saarthakchats.github.io/rabbish/)
screenshot 2018-11-15 at 6 12 29 pm

### CODE REVIEW

**Comment by Ryan10145** [comment]
@saarthakchats #26 is a currently open PR that addresses this issue already.

**Comment by saarthakchats** [comment]
That PR is conflicting, without a preview link and other problems

**Comment by BolajiAyodeji** [comment]
You should add a description of your new fix?

**Comment by Aishh2k** [comment]
@Ryan10145 I have solved all the problems! Please review PR #26

**Pull request closed without merging**
