### PR TITLE
[Fixed #34] Add mobile navbar 

### LINKED ISSUE #34: Couldn't access to the navbar in small screens.
@mariobehling Can I work on this? Could you please assign me?

Couldn't see the navigation bar in smaller screens.
image

I am going to fix it.

### PR DESCRIPTION
**Pull request by STEdirisuriya**
Fixed #34 

## Add mobile navigation bar.
**Before**
image
**Now**
image

## Add a scroll
image

**Preview link -**
https://stedirisuriya.github.io/2019.fossasia.org/

### CODE REVIEW

**Comment by sarnava1** [comment]
LGTM.

**Comment by STEdirisuriya** [comment]
@stealthanthrax I fixed it. Could you please check it again now?
image

**Comment by stealthanthrax** [comment]
Your PR makes the dropdown on the Desktop sized screens, translucent too. Please fix that.
screenshot 2018-11-19 at 8 17 36 pm

**Comment by STEdirisuriya** [comment]
@stealthanthrax @ms10398  I have done the changes.

**Comment by STEdirisuriya** [comment]
@stealthanthrax @ms10398 @sarnava1 @jogendra  Here's my PR was to re-adding the mobile nav bar button which has removed. After that I have to added a dropdown for stop overflowing menu and I added a scroll bar to stop overflowing dropdown. In this case I have used the same theme like in other sites of fossasia. In these sites there is a color difference in dropdown beacuse it using same styles for dropdown in PC and mobile both. If I changing colour I think we have to change colors in all of the sites. So could you please merge this PR and start new issue for that?

**Comment by stealthanthrax** [comment]
You can write a media query for that. I don't think to approve the task just for the sake of completion should be the way to proceed
>>In these sites there is a color difference in dropdown because it using same styles for dropdown in PC and mobile both

**Comment by STEdirisuriya** [comment]
@pythongiant  @akshatnitd I have resolve conflicts.

**Comment by STEdirisuriya** [comment]
@stealthanthrax I have resolved that problem also. 
### In mobile screen
image
### In desktop screen.
image

Thank you!

**Pull request merged**
