### PR TITLE
Resolved the button issue

### PR DESCRIPTION
**Pull request by naveentvelu**
Fixes https://github.com/fossasia/2019.fossasia.org/issues/47
Before:
screenshot from 2018-12-07 23-55-09
After:
screenshot from 2018-12-07 23-55-27

### CODE REVIEW

**Comment by naveentvelu** [comment]
@mariobehling The button for Exhibition Booklet should be hollow right? or all three?

**Comment by mariobehling** [comment]
Rather than changing the button itself, could you please check why the hollow-btn is working on the start page and does not work on the page here? I think there is a link issue to the css or so somewhere. Could you please investigate? Thanks.

**Comment by mariobehling** [comment]
Whenever you make a PR, please also provide a preview link.

**Comment by naveentvelu** [comment]
@mariobehling The error is because, the btn-hollow is defined in theme-lava.css which is being overwritten by custom.css.
The css which are over-writing the btn-hollow are,
  .schedule a {
  color: #E12B00;
  border: none;
}
.schedule a:hover {
  color: #E12B00;
  text-decoration: underline;
  border: none;
}
.schedule a:visited {
  color: #B82300;
  text-decoration: none;
  border: none;
}

I guess these are used in some other places.
One solution for this can be to include "!important" in btn-hollow and other btn inside theme-lava.css
Your views on this?

**Comment by naveentvelu** [comment]
I am new to opensource. Kindly please tell me how to generate a preview link.
@akshatnitd

**Comment by mariobehling** [comment]
Closing due to inactivity. Please reopen once you would like to continue. Thanks.

**Pull request closed without merging**
