### PR TITLE
Added translation feature 

### LINKED ISSUE #38: The site supports only one language
Please add a translation feature in the site

I am working on this issue.

### PR DESCRIPTION
**Pull request by sahilsaha7773**
Added Google translate in such a way that the names of persons don't get translated to weird words.

tr

- Preview link : https://sahilsaha7773.github.io/2019.fossasia.org/
- Fixes #38

### CODE REVIEW

**Comment by sahilsaha7773** [comment]
please merge

**Comment by sahilsaha7773** [comment]
@pythongiant I don't think it is breaking the navbar

**Comment by sahilsaha7773** [comment]
@jogendra Please review

**Comment by Ryan10145** [comment]
image
image


Looks really odd in the center, it should probably be in the top right if it is necessary. Also, the logo/link for the Google translate doesn't fit in the navbar and is also super hard to see.

**Comment by sahilsaha7773** [comment]
ok I am doing the changes

**Pull request closed without merging**
